name = "solid-drizzle-example"
main = "dist/server/entry-server.js"
compatibility_date = "2025-04-02"

[[d1_databases]]
binding = "DB"
database_name = "solid-drizzle-db"
database_id = "deb3c5a5-0e39-499d-ae4d-fef017c933ec"
migrations_dir = "drizzle/migrations" 